### ISSUE TITLE
arduinos

### ISSUE THREAD

**Issue by alexgillespie02** [jakethakur22/AUV-Project#4]
I have both of the Arduinos plugged into my computer because I need both of them to be (one is the sender and one is the transmitter) but there are about 7 different ports and I am unsure which one is meant for each Arduino since I am getting an error message saying problem uploading to board and I am not even sure the Arduinos are wired correctly because I had to make assumptions and guesses based off of the diagram on the website I am using to set them up. Any ideas?

**Comment by jakethakur** [comment]
If they’re the school’s arduinos, make sure you’ve installed the driver software: https://github.com/jakethakur22/AUV-Project/wiki/Using-an-Arduino-Clone

If you’ve done that, have you tried changing the COM around in the port menu of the arduino IDE?
